#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

apt-get update
apt-get install -y haproxy

printf %s "
frontend ambre-tech-frontend
        bind *:80
        mode http
        default_backend ambre-tech-backend
backend ambre-tech-backend
        balance roundrobin
        server 116303-web-01 34.227.92.178:80 check
        server 116303-web-02 54.196.27.201:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
